spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/db/cac;
    username: sa
    password: ""
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      show_sql: true